// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { resolve } from "path";
import { existsSync, readFileSync } from "fs";
import { defineConfig } from "prisma/config";

// Determine if we're running from root or apps/api/
const cwd = process.cwd();
const isRoot = !cwd.includes("apps/api") || cwd.endsWith("banking-ledger");

// Find project root and api directory
const projectRoot = isRoot ? cwd : resolve(cwd, "../..");
const apiDir = isRoot ? resolve(projectRoot, "apps/api") : cwd;

// Always load .env from project root
const rootEnvPath = resolve(projectRoot, ".env");

if (!existsSync(rootEnvPath)) {
  throw new Error(
    `Could not find .env file at: ${rootEnvPath}\n` +
    `Current working directory: ${cwd}\n` +
    `Project root: ${projectRoot}`
  );
}

// Debug: Read and show all DATABASE_URL lines from the file
try {
  const envContent = readFileSync(rootEnvPath, "utf-8");
  const dbUrlLines = envContent
    .split("\n")
    .map((line, idx) => ({ line: line.trim(), num: idx + 1 }))
    .filter(({ line }) => line.includes("DATABASE_URL") && !line.startsWith("#"));
  
  console.log(`\n📄 Found ${dbUrlLines.length} DATABASE_URL line(s) in .env file:`);
  dbUrlLines.forEach(({ line, num }) => {
    const masked = line.replace(/:([^:@]+)@/, ':****@');
    console.log(`  Line ${num}: ${masked}`);
  });
} catch (err) {
  console.warn(`Could not read .env file for debugging: ${err}`);
}

// Check if DATABASE_URL is already set in environment (before loading .env)
const existingDbUrl = process.env.DATABASE_URL;
if (existingDbUrl) {
  console.warn(`⚠ WARNING: DATABASE_URL already set in environment: ${existingDbUrl.replace(/:([^:@]+)@/, ':****@')}`);
  console.warn(`⚠ This will override .env file values unless we override it`);
}

// Load environment variables into process.env
// Use override: true to ensure .env file values override any existing env vars
const result = config({ path: rootEnvPath, override: true });

if (result.error) {
  console.warn(`Warning: Error loading .env file: ${result.error.message}`);
} else {
  console.log(`✓ Loaded .env from: ${rootEnvPath}`);
  // Show what was parsed from .env (if available)
  if (result.parsed) {
    const envDbUrl = result.parsed.DATABASE_URL;
    if (envDbUrl) {
      console.log(`✓ Found DATABASE_URL in .env: ${envDbUrl.replace(/:([^:@]+)@/, ':****@')}`);
    } else {
      console.warn(`⚠ No DATABASE_URL found in .env file`);
    }
    
    // Check for multiple DATABASE_URL entries
    const allDbUrls = Object.keys(result.parsed).filter(key => key === 'DATABASE_URL');
    if (allDbUrls.length > 1) {
      console.warn(`⚠ WARNING: Multiple DATABASE_URL entries found in .env file!`);
    }
  }
}

// Get DATABASE_URL from process.env (after dotenv loads it)
// Prefer non-localhost URLs if multiple exist
let databaseUrl = process.env.DATABASE_URL;

// If we got a localhost URL, check if there's a non-localhost one in the parsed result
if (databaseUrl && databaseUrl.includes('localhost')) {
  console.warn(`⚠ WARNING: DATABASE_URL points to localhost. Looking for alternative...`);
  if (result.parsed) {
    // Check if there's a PRISMA_DATABASE_URL we can derive from, or look for other patterns
    const prismaUrl = process.env.PRISMA_DATABASE_URL;
    if (prismaUrl && prismaUrl.includes('db.prisma.io')) {
      console.warn(`⚠ Found PRISMA_DATABASE_URL but it's an Accelerate URL (not suitable for introspection)`);
    }
  }
}

if (!databaseUrl) {
  throw new Error(
    `DATABASE_URL is not set. Checked:\n` +
    `  - Environment variables: ${existingDbUrl ? 'found' : 'not found'}\n` +
    `  - .env file at: ${rootEnvPath}\n` +
    `  - Current working directory: ${cwd}`
  );
}

// Debug: Show what URL we're using (masked for security)
const maskedUrl = databaseUrl.replace(/:([^:@]+)@/, ':****@');
console.log(`✓ Final DATABASE_URL being used: ${maskedUrl}`);

// Schema and migrations paths - use absolute paths so they work from anywhere
const schemaPath = resolve(apiDir, "prisma/schema.prisma");
const migrationsPath = resolve(apiDir, "prisma/migrations");

export default defineConfig({
  schema: schemaPath,
  migrations: {
    path: migrationsPath,
  },
  engine: "classic",
  datasource: {
    url: databaseUrl,
  },
});
